// <auto-generated />
namespace CMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DictionaryLink_TicketLink_Indices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DictionaryLink_TicketLink_Indices));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280858345_DictionaryLink_TicketLink_Indices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
